spring:
  datasource:
    # >= 6.x com.mysql.cj.jdbc.Driver
    # <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 指定namespace
        #namespace: f2320048-5c9d-4476-a249-7d508e227703
        # 指定集群名称 NJ
        # cluster-name: NJ

  application:
    name: user-center

server:
  port: 8081
