# 所有环境公用的配置属性
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app-name: spring-boot-demo
  author: yicj
  email: 626659321@qq.com

# 应用启动时默认profile指定
spring:
  profiles:
    active: dev
# 连字符
---
# profile=x 的专用属性，也就是某个环境下的专用属性
# 开发环境
spring:
  profiles: dev

# 连字符
---
# profile=y 的专用属性，也就是某个环境下的专用属性
# 生产环境
spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    max-threads: 300
